### ISSUE TITLE
Holding attack and scrolling causes weapon switcher to instantly select the next weapon

### ISSUE THREAD

**Issue by willox** [Facepunch/garrysmod-issues#2873]
it should probably not do that

**Comment by LuaTenshi** [comment]
Just got the dev branch of gmod to see if it's fixed on there. This issue seems to still be there. (The dev branch was updated 7 hours ago.)

**Comment by robotboy655** [comment]
@LuaTenshi I cannot reproduce. This should be fixed in all version of the game.

**Comment by LuaTenshi** [comment]
Hmm strange, I'll try to get a video of it up ASAP. Not doing anything
special, also cleared my addons and verified game cache to make sure it
wasn't a fluke. Are you trying this in single player or on a server?
Because I forgot to mention that this was happening to me on servers not
sure if it happens on singleplayer but I'll check.

**Comment by roboderpy** [comment]
@LuaTenshi Is wrong, not happening on Dev branch

**Comment by LuaTenshi** [comment]
Really strange that you guys can't seem to replicate this. Both me and a friend are still having this issue in fact if it persists I'll attempt to provide as much info as I possibly can. Including video. But maybe Garry just hates me idk.

**Comment by LuaTenshi** [comment]
Happens all the time for me, when holding mouse1, and then scrolling it goes into weapons select. 

![Still broken?](https://puu.sh/s5Ha5/4732942883.gif)

Is this intended?
