### ISSUE TITLE
Lag compensation not setting up pose parameters correctly

### ISSUE THREAD

**Issue by GrandpaTroll** [Facepunch/garrysmod-issues#3683]
I know some animations like the aim_yaw is not networked but it's not even trying to set the cycles/poseparamaers when trying to lag compensate the players.

Red is server | Blue is client
![image](https://user-images.githubusercontent.com/28169447/50040369-44c05980-ffff-11e8-8919-0b1f41352c3a.png)

Just have someone spin at a slow rate and you're bound to have desync (Blood on your screen but server doesn't acknowledges it)

**Comment by Bo98** [comment]
Yes, the Source engine does not support pose parameters lag compensation out-of-the-box.

This was a big thing in CS:GO and was fixed via something like [this](
https://github.com/ValveSoftware/source-sdk-2013/pull/331).

What I don’t know is if this fix was ever merged into GMod. I know @willox made @robotboy655 and _Kilburn aware at the time (this was before @willox joined the team), but I’m not sure if anything happened or not. Perhaps one of them can tell me.

**Comment by Jermany** [comment]
@GrandpaTroll found this out by making backtracking and watching noob dogs livestream. im watching u buddy, im watching u.

**Comment by willox** [comment]
I've changed some stuff, so please try reproducing this on the dev branch again.

**Comment by GrandpaTroll** [comment]
![image](https://user-images.githubusercontent.com/28169447/50125215-0c01c980-0225-11e9-90f6-95271a6700b6.png)
Still appears to be desynced

On my own server with net_fakelag of 200

**Comment by willox** [comment]
The server was updated on the dev branch?

**Comment by GrandpaTroll** [comment]
Yes it was on my own local server

**Comment by GrandpaTroll** [comment]
A week has passed, It appears to seems theres no signs of life.

**Comment by Raox2** [comment]
Would like to see this fixed. A source of frustration for many players, probably across years across various kinds of gamemodes.

**Comment by 11Lee1** [comment]
FeelsBadMan if someone turns really fast they're characters angles rendered on other peoples clients wont match the server

**Comment by 11Lee1** [comment]
oh yeah, I forgot to mention this as well since I was memeing, can you up the default value of m_flTeleportDistanceSqr?  A lot of servers have a boner for running their shit on extremely low tickrate making it really easy to break the backtracking done by the server in player_lagcompensation making hit registration for clients kinda asshole aswell wont really help much since the players position on the client will get interpolated perframe etc etc etc but it's better than someone running and breaking lagcomp

**Comment by willox** [comment]
I don't think this is related to pose params. Can you try again on the latest dev branch?

**Comment by Raox2** [comment]
Apparently it has been made recently worse. I believe it is related to pose parameters, as these don't sync correctly unless players have velocity/rotate more than 45 degrees. Would be worth looking at.

**Comment by willox** [comment]
Were you on the dev branch? The pose parameters have always been out of sync, so if you're just going to say it's suddenly worse I'm probably not going to look.

**Comment by 11Lee1** [comment]
please just network their currentfeetyaw like as thats used for calculating the angle the player's rendered at, wont really help with other pose parameters being out of sync but will still help immensely

**Comment by willox** [comment]
Nothing will change if issues can not be reproduced.

**Comment by 11Lee1** [comment]
easy. https://www.youtube.com/watch?v=BboNPKmp1O4
`local swap = false;

hook.Add("StartCommand","hkStartCommand",function(player,pCmd)
    if(player != Entity(1)/*local player on local server*/)then
        swap = !swap;
        pCmd:SetViewAngles(Angle(89,swap and 0 or 180,0));
    end
end);`
https://github.com/ValveSoftware/source-sdk-2013/blob/0d8dceea4310fde5706b3ce1c70609d72a38efdf/sp/src/game/shared/Multiplayer/multiplayer_animstate.cpp#L1648

Keep in mind this is on a **66 tick server** so it's much harder to replicate this for a legitimate player, but as they tickrate gets lower it should get easier and easier to replicate for a legit player.  Also keep in mind a fair amount of the gmod servers are running <= 33 tick for gamemodes like ttt and <= 16 tick for darkrp or roleplay related gamemodes.

example #2 using a 16 tickrate server https://www.youtube.com/watch?v=EluYZ1pfisk

**Comment by LShirohana** [comment]
Confirmed this myself, and is extremely evident at 16 tickrate. God help you if you try to use a fast-firing gun on a player at this tickrate.

**Comment by 11Lee1** [comment]
any developments on this?

**Comment by mcNuggets1** [comment]
I'm running on 33 ticks and nearly every second hit is a fake.

**Comment by angelfor3v3r** [comment]
The issue happens a lot when a user is rotating and making their poses update, this causes a massive desync on the server vs client. You can reproduce it easy with a rotating player swinging a  crowbar even. The client cycle is out of sync.

Regardless, these changes have been implemented in CS:GO a long time ago. Shouldn’t that alone warrant a change for GMod? Hell, even a low tick delay due to clientside view interpolation causes massive client desync.

**Comment by Raox2** [comment]
Could send the line(s)/associated changes on the gmod discord to Rubat/code_gs?

**Comment by Erlite** [comment]
Should probably re-open this as this still occurs, unless this was fixed?

**Comment by xCynDev** [comment]
@robotboy655 any way of porting the above over? This would literally fix this issue.
