### ISSUE TITLE
RecordSteamInterfaceCreation Issue on LAN Linux Servers

### ISSUE THREAD

**Issue by garryspins** [Facepunch/garrysmod-issues#4763]
### Details
Whenever I run SRCDS, with or without options (map, workshop, etc) throughout it starting it spams 
`RecordSteamInterfaceCreation (PID <ProgramID Here>): Something / Somethingelse`
I've tried everything to solve this issue, reinstalling the server entirely, running it without addons and whatnot
no matter what i do it doesn't show in the LAN section of the legacy browser or "Local Network" on the HTML menu

### Steps to reproduce
I have actually no clue what could possibly be causing the issue, it was working perfectly fine the night before this issue

### Log
<details>
 <summary>Console Output Without Addons</summary>
 <pre>
WARNING: No map specified! Defaulting to gm_construct
Auto detecting CPU
Using default binary: ./srcds_linux
Server will auto-restart if there is a crash.

WARNING: Failed to load 32-bit libtinfo.so.5 or libncurses.so.5.
  Please install (lib32tinfo5 / ncurses-libs.i686 / equivalent) to enable readline.

Couldn't load shader dll: game_shader_generic_garrysmod_srv.soConVarRef mat_dxlevel doesn't point to an existing ConVar
Game_srv.so loaded for "Garry's Mod"
Setting breakpad minidump AppID = 4000
Initializing Steam libraries for Workshop..
CAppInfoCacheReadFromDiskThread took 5 milliseconds to initialize
RecordSteamInterfaceCreation (PID 28483): SteamGameServer012 / GameServer
RecordSteamInterfaceCreation (PID 28483): SteamUtils009 / Utils
RecordSteamInterfaceCreation (PID 28483): SteamGameServer012 / 
RecordSteamInterfaceCreation (PID 28483): SteamUtils009 / 
RecordSteamInterfaceCreation (PID 28483): SteamNetworking005 / 
RecordSteamInterfaceCreation (PID 28483): SteamGameServerStats001 / 
RecordSteamInterfaceCreation (PID 28483): STEAMHTTP_INTERFACE_VERSION003 / 
RecordSteamInterfaceCreation (PID 28483): STEAMINVENTORY_INTERFACE_V003 / 
RecordSteamInterfaceCreation (PID 28483): STEAMUGC_INTERFACE_VERSION012 / 
RecordSteamInterfaceCreation (PID 28483): STEAMAPPS_INTERFACE_VERSION008 / 
[S_API FAIL] Tried to access Steam interface SteamUser020 before SteamAPI_Init succeeded.
RecordSteamInterfaceCreation (PID 28483): SteamGameServer012 / 
RecordSteamInterfaceCreation (PID 28483): SteamUtils009 / 
RecordSteamInterfaceCreation (PID 28483): SteamNetworking005 / 
RecordSteamInterfaceCreation (PID 28483): SteamGameServerStats001 / 
RecordSteamInterfaceCreation (PID 28483): STEAMHTTP_INTERFACE_VERSION003 / 
RecordSteamInterfaceCreation (PID 28483): STEAMINVENTORY_INTERFACE_V003 / 
RecordSteamInterfaceCreation (PID 28483): STEAMUGC_INTERFACE_VERSION012 / 
RecordSteamInterfaceCreation (PID 28483): STEAMAPPS_INTERFACE_VERSION008 / 
WS: No +host_workshop_collection or it is invalid!
CApplicationManagerPopulateThread took 277 milliseconds to initialize (will have waited on CAppInfoCacheReadFromDiskThread)
Unknown command "cl_cmdrate"
Unknown command "cl_updaterate"
Unknown command "rate"
Network: IP 127.0.1.1, mode MP, dedicated Yes, ports 27015 SV / 27005 CL
Error loading cfg/trusted_keys_base.txt
Error loading cfg/pure_server_minimal.txt
PREP OK
ConVarRef room_type doesn't point to an existing ConVar
Executing dedicated server config file server.cfg
Using map cycle file cfg/mapcycle.txt.
Initializing Steam libraries for secure Internet server
CAppInfoCacheReadFromDiskThread took 5 milliseconds to initialize
RecordSteamInterfaceCreation (PID 28483): SteamGameServer012 / GameServer
RecordSteamInterfaceCreation (PID 28483): SteamUtils009 / Utils
RecordSteamInterfaceCreation (PID 28483): SteamGameServer012 / 
RecordSteamInterfaceCreation (PID 28483): SteamUtils009 / 
RecordSteamInterfaceCreation (PID 28483): SteamNetworking005 / 
RecordSteamInterfaceCreation (PID 28483): SteamGameServerStats001 / 
RecordSteamInterfaceCreation (PID 28483): STEAMHTTP_INTERFACE_VERSION003 / 
RecordSteamInterfaceCreation (PID 28483): STEAMINVENTORY_INTERFACE_V003 / 
RecordSteamInterfaceCreation (PID 28483): STEAMUGC_INTERFACE_VERSION012 / 
RecordSteamInterfaceCreation (PID 28483): STEAMAPPS_INTERFACE_VERSION008 / 
No account token specified; logging into anonymous game server account.  (Use sv_setsteamaccount to login to a persistent account.)
RecordSteamInterfaceCreation (PID 28483): SteamGameServer012 / 
RecordSteamInterfaceCreation (PID 28483): SteamUtils009 / 
RecordSteamInterfaceCreation (PID 28483): SteamNetworking005 / 
RecordSteamInterfaceCreation (PID 28483): SteamGameServerStats001 / 
RecordSteamInterfaceCreation (PID 28483): STEAMHTTP_INTERFACE_VERSION003 / 
RecordSteamInterfaceCreation (PID 28483): STEAMINVENTORY_INTERFACE_V003 / 
RecordSteamInterfaceCreation (PID 28483): STEAMUGC_INTERFACE_VERSION012 / 
RecordSteamInterfaceCreation (PID 28483): STEAMAPPS_INTERFACE_VERSION008 / 
CApplicationManagerPopulateThread took 252 milliseconds to initialize (will have waited on CAppInfoCacheReadFromDiskThread)
Connection to Steam servers successful.
   Public IP is _______.
Assigned anonymous gameserver Steam ID [A-1:3845997576(16045)].
VAC secure mode is activated.
</pre>
</details>

<details>
<summary>Console Output With Workshop Addons (<a href="https://steamcommunity.com/sharedfiles/filedetails/?id=2020691871">Workshop</a>)</summary>
<pre>
WARNING: No map specified! Defaulting to gm_construct
Auto detecting CPU
Using default binary: ./srcds_linux
Server will auto-restart if there is a crash.

WARNING: Failed to load 32-bit libtinfo.so.5 or libncurses.so.5.
  Please install (lib32tinfo5 / ncurses-libs.i686 / equivalent) to enable readline.

Couldn't load shader dll: game_shader_generic_garrysmod_srv.soConVarRef mat_dxlevel doesn't point to an existing ConVar
Game_srv.so loaded for "Garry's Mod"
Setting breakpad minidump AppID = 4000
Initializing Steam libraries for Workshop..
CAppInfoCacheReadFromDiskThread took 6 milliseconds to initialize
RecordSteamInterfaceCreation (PID 29279): SteamGameServer012 / GameServer
RecordSteamInterfaceCreation (PID 29279): SteamUtils009 / Utils
RecordSteamInterfaceCreation (PID 29279): SteamGameServer012 / 
RecordSteamInterfaceCreation (PID 29279): SteamUtils009 / 
RecordSteamInterfaceCreation (PID 29279): SteamNetworking005 / 
RecordSteamInterfaceCreation (PID 29279): SteamGameServerStats001 / 
RecordSteamInterfaceCreation (PID 29279): STEAMHTTP_INTERFACE_VERSION003 / 
RecordSteamInterfaceCreation (PID 29279): STEAMINVENTORY_INTERFACE_V003 / 
RecordSteamInterfaceCreation (PID 29279): STEAMUGC_INTERFACE_VERSION012 / 
RecordSteamInterfaceCreation (PID 29279): STEAMAPPS_INTERFACE_VERSION008 / 
[S_API FAIL] Tried to access Steam interface SteamUser020 before SteamAPI_Init succeeded.
RecordSteamInterfaceCreation (PID 29279): SteamGameServer012 / 
RecordSteamInterfaceCreation (PID 29279): SteamUtils009 / 
RecordSteamInterfaceCreation (PID 29279): SteamNetworking005 / 
RecordSteamInterfaceCreation (PID 29279): SteamGameServerStats001 / 
RecordSteamInterfaceCreation (PID 29279): STEAMHTTP_INTERFACE_VERSION003 / 
RecordSteamInterfaceCreation (PID 29279): STEAMINVENTORY_INTERFACE_V003 / 
RecordSteamInterfaceCreation (PID 29279): STEAMUGC_INTERFACE_VERSION012 / 
RecordSteamInterfaceCreation (PID 29279): STEAMAPPS_INTERFACE_VERSION008 / 
RecordSteamInterfaceCreation (PID 29279): STEAMUGC_INTERFACE_VERSION012 / UGC
RecordSteamInterfaceCreation (PID 29279): SteamGameServer012 / GameServer
CApplicationManagerPopulateThread took 247 milliseconds to initialize (will have waited on CAppInfoCacheReadFromDiskThread)
RecordSteamInterfaceCreation (PID 29279): SteamGameServer012 / GameServer
RecordSteamInterfaceCreation (PID 29279): SteamGameServer012 / GameServer
RecordSteamInterfaceCreation (PID 29279): SteamGameServer012 / GameServer
RecordSteamInterfaceCreation (PID 29279): SteamGameServer012 / GameServer
RecordSteamInterfaceCreation (PID 29279): SteamGameServer012 / GameServer
WS: Waiting for Steam to log us in.....
RecordSteamInterfaceCreation (PID 29279): STEAMUGC_INTERFACE_VERSION012 / UGC
WS: Fetching collection info...
Processing collection 2020691871...
RecordSteamInterfaceCreation (PID 29279): STEAMUGC_INTERFACE_VERSION012 / UGC
RecordSteamInterfaceCreation (PID 29279): STEAMUGC_INTERFACE_VERSION012 / UGC
RecordSteamInterfaceCreation (PID 29279): STEAMUGC_INTERFACE_VERSION012 / UGC
RecordSteamInterfaceCreation (PID 29279): SteamUtils009 / Utils
RecordSteamInterfaceCreation (PID 29279): SteamUtils009 / Utils
RecordSteamInterfaceCreation (PID 29279): SteamUtils009 / Utils
RecordSteamInterfaceCreation (PID 29279): SteamUtils009 / Utils
RecordSteamInterfaceCreation (PID 29279): STEAMUGC_INTERFACE_VERSION012 / UGC
RecordSteamInterfaceCreation (PID 29279): STEAMUGC_INTERFACE_VERSION012 / UGC
RecordSteamInterfaceCreation (PID 29279): STEAMUGC_INTERFACE_VERSION012 / UGC
RecordSteamInterfaceCreation (PID 29279): STEAMUGC_INTERFACE_VERSION012 / UGC
RecordSteamInterfaceCreation (PID 29279): STEAMUGC_INTERFACE_VERSION012 / UGC
RecordSteamInterfaceCreation (PID 29279): SteamUtils009 / Utils
RecordSteamInterfaceCreation (PID 29279): SteamUtils009 / Utils
RecordSteamInterfaceCreation (PID 29279): SteamUtils009 / Utils
RecordSteamInterfaceCreation (PID 29279): SteamUtils009 / Utils
RecordSteamInterfaceCreation (PID 29279): STEAMUGC_INTERFACE_VERSION012 / UGC
RecordSteamInterfaceCreation (PID 29279): STEAMUGC_INTERFACE_VERSION012 / UGC
RecordSteamInterfaceCreation (PID 29279): STEAMUGC_INTERFACE_VERSION012 / UGC
RecordSteamInterfaceCreation (PID 29279): STEAMUGC_INTERFACE_VERSION012 / UGC
RecordSteamInterfaceCreation (PID 29279): STEAMUGC_INTERFACE_VERSION012 / UGC
RecordSteamInterfaceCreation (PID 29279): STEAMUGC_INTERFACE_VERSION012 / UGC
RecordSteamInterfaceCreation (PID 29279): STEAMUGC_INTERFACE_VERSION012 / UGC
RecordSteamInterfaceCreation (PID 29279): STEAMUGC_INTERFACE_VERSION012 / UGC
RecordSteamInterfaceCreation (PID 29279): STEAMUGC_INTERFACE_VERSION012 / UGC
RecordSteamInterfaceCreation (PID 29279): STEAMUGC_INTERFACE_VERSION012 / UGC
RecordSteamInterfaceCreation (PID 29279): STEAMUGC_INTERFACE_VERSION012 / UGC
RecordSteamInterfaceCreation (PID 29279): STEAMUGC_INTERFACE_VERSION012 / UGC
   Collection 'Dev Server Collection'
   11 new addons
WS: Finished!

WS: Processing 11 addons...
Processing addon 11: [Official] Precision Tool (104482086)...
RecordSteamInterfaceCreation (PID 29279): STEAMUGC_INTERFACE_VERSION012 / UGC
RecordSteamInterfaceCreation (PID 29279): STEAMUGC_INTERFACE_VERSION012 / UGC
   Mounted!
Processing addon 10: PAC3 (104691717)...
RecordSteamInterfaceCreation (PID 29279): STEAMUGC_INTERFACE_VERSION012 / UGC
RecordSteamInterfaceCreation (PID 29279): STEAMUGC_INTERFACE_VERSION012 / UGC
   Mounted!
Processing addon 9: Star Wars Lightsabers (111412589)...
RecordSteamInterfaceCreation (PID 29279): STEAMUGC_INTERFACE_VERSION012 / UGC
RecordSteamInterfaceCreation (PID 29279): STEAMUGC_INTERFACE_VERSION012 / UGC
   Mounted!
Processing addon 8: M9K Assault Rifles (128089118)...
RecordSteamInterfaceCreation (PID 29279): STEAMUGC_INTERFACE_VERSION012 / UGC
RecordSteamInterfaceCreation (PID 29279): STEAMUGC_INTERFACE_VERSION012 / UGC
   Mounted!
Processing addon 7: M9K Specialties (144982052)...
RecordSteamInterfaceCreation (PID 29279): STEAMUGC_INTERFACE_VERSION012 / UGC
RecordSteamInterfaceCreation (PID 29279): STEAMUGC_INTERFACE_VERSION012 / UGC
   Mounted!
Processing addon 6: Wiremod (160250458)...
RecordSteamInterfaceCreation (PID 29279): STEAMUGC_INTERFACE_VERSION012 / UGC
RecordSteamInterfaceCreation (PID 29279): STEAMUGC_INTERFACE_VERSION012 / UGC
   Mounted!
Processing addon 5: Tools Pack (935360623)...
RecordSteamInterfaceCreation (PID 29279): STEAMUGC_INTERFACE_VERSION012 / UGC
RecordSteamInterfaceCreation (PID 29279): STEAMUGC_INTERFACE_VERSION012 / UGC
   Mounted!
Processing addon 4: SCP: Containment Breach - Unity: SCP-106 PM & NPC (1267850660)...
RecordSteamInterfaceCreation (PID 29279): STEAMUGC_INTERFACE_VERSION012 / UGC
RecordSteamInterfaceCreation (PID 29279): STEAMUGC_INTERFACE_VERSION012 / UGC
   Mounted!
Processing addon 3: GmodAdminSuite (1595332211)...
RecordSteamInterfaceCreation (PID 29279): STEAMUGC_INTERFACE_VERSION012 / UGC
RecordSteamInterfaceCreation (PID 29279): STEAMUGC_INTERFACE_VERSION012 / UGC
   Mounted!
Processing addon 2: Gmod Blueprints (Visual Scripting) (1986113409)...
RecordSteamInterfaceCreation (PID 29279): STEAMUGC_INTERFACE_VERSION012 / UGC
RecordSteamInterfaceCreation (PID 29279): STEAMUGC_INTERFACE_VERSION012 / UGC
   Mounted!
Processing addon 1: gm_neon_construct (2028452231)...
RecordSteamInterfaceCreation (PID 29279): STEAMUGC_INTERFACE_VERSION012 / UGC
RecordSteamInterfaceCreation (PID 29279): STEAMUGC_INTERFACE_VERSION012 / UGC
   Mounted!
WS: Finished!
Addon 'M9K Specialties' (144982052) contains file from 128089118: 'lua/effects/m9k_effect_mad_penetration_trace/init.lua'
Addon 'M9K Specialties' (144982052) contains file from 128089118: 'lua/effects/m9k_effect_mad_ricochet_trace/init.lua'
Addon 'M9K Specialties' (144982052) contains file from 128089118: 'lua/effects/m9k_rg_muzzle_rifle/init.lua'
Addon 'M9K Specialties' (144982052) contains file from 128089118: 'lua/entities/m9k_ammo_357/shared.lua'
Addon 'M9K Specialties' (144982052) contains file from 128089118: 'lua/entities/m9k_ammo_ar2/shared.lua'
Addon 'M9K Specialties' (144982052) contains file from 128089118: 'lua/entities/m9k_ammo_buckshot/shared.lua'
Addon 'M9K Specialties' (144982052) contains file from 128089118: 'lua/entities/m9k_ammo_pistol/shared.lua'
Addon 'M9K Specialties' (144982052) contains file from 128089118: 'lua/entities/m9k_ammo_smg/shared.lua'
Addon 'M9K Specialties' (144982052) contains file from 128089118: 'lua/entities/m9k_ammo_sniper_rounds/shared.lua'
Addon 'M9K Specialties' (144982052) contains file from 128089118: 'lua/entities/m9k_ammo_winchester/shared.lua'
Addon 'M9K Specialties' (144982052) contains file from 128089118: 'lua/weapons/bobs_blacklisted/shared.lua'
Addon 'M9K Specialties' (144982052) contains file from 128089118: 'lua/weapons/bobs_gun_base/shared.lua'
Addon 'M9K Specialties' (144982052) contains file from 128089118: 'lua/weapons/bobs_scoped_base/cl_init.lua'
Addon 'M9K Specialties' (144982052) contains file from 128089118: 'lua/weapons/bobs_scoped_base/init.lua'
Addon 'M9K Specialties' (144982052) contains file from 128089118: 'lua/weapons/bobs_scoped_base/shared.lua'
Addon 'M9K Specialties' (144982052) contains file from 128089118: 'lua/weapons/bobs_shotty_base/cl_init.lua'
Addon 'M9K Specialties' (144982052) contains file from 128089118: 'lua/weapons/bobs_shotty_base/init.lua'
Addon 'M9K Specialties' (144982052) contains file from 128089118: 'lua/weapons/bobs_shotty_base/shared.lua'
RecordSteamInterfaceCreation (PID 29279): STEAMUGC_INTERFACE_VERSION012 / UGC
Addon 'Tools Pack' (935360623) contains file from 104482086: 'lua/weapons/gmod_tool/stools/precision.lua'
RecordSteamInterfaceCreation (PID 29279): STEAMUGC_INTERFACE_VERSION012 / UGC
RecordSteamInterfaceCreation (PID 29279): STEAMUGC_INTERFACE_VERSION012 / UGC
RecordSteamInterfaceCreation (PID 29279): STEAMUGC_INTERFACE_VERSION012 / UGC
Unknown command "cl_cmdrate"
Unknown command "cl_updaterate"
Unknown command "rate"
Network: IP 127.0.1.1, mode MP, dedicated Yes, ports 27015 SV / 27005 CL
Error loading cfg/trusted_keys_base.txt
Error loading cfg/pure_server_minimal.txt
PREP OK
[AddCSLuaFile] Couldn't find 'gmodadminsuite_lua_functions.lua' (@lua/autorun/gmodadminsuite.lua (line 120))
[AddCSLuaFile] Couldn't find 'gmodadminsuite_config.lua' (@lua/autorun/gmodadminsuite.lua (line 121))
[GmodAdminSuite] [================================   GmodAdminSuite   =================================]
[GmodAdminSuite] [ Version: v1                                                                         ]
[GmodAdminSuite] [                                                                                     ]
[GmodAdminSuite] [ [INFO] Loading configs...                                                           ]
[FATAL] Looks like the GmodAdminSuite Config Addon has not been installed to your server: https://gmodsto.re/gmodadminsuite-config-addon
You need to install this addon in order to use & configure GmodAdminSuite.
Weapon Strip con var created
Penetration/ricochet con var created
Recoil con var created
Ammo crate detonation con var created
Damage Multiplier con var created
Default Clip con var created
Unique Slots con var created
Explosive Nerve Gas con var created
Davy Crockett timer created

     _____             _____               _         _             
    |     |___ ___ ___|  _  |___ ___ _____|_|___ ___|_|___ ___ ___ 
    |  |  | . | -_|   |   __| -_|  _|     | |_ -|_ -| | . |   |_ -|
    |_____|  _|___|_|_|__|  |___|_| |_|_|_|_|___|___|_|___|_|_|___|
          |_|                                                      

  [=================================================================]
  [                          Version: v1.0                          ]
  [      https://github.com/WilliamVenner/GLua-OpenPermissions      ]
  [=================================================================]

https://gmodsto.re/openpermissions-config-addon
You need to install this addon in order to use & configure OpenPermissions.
[PAC3] Loaded total 13 particle systems
Wiremod Version 'Workshop' loaded
[ACD] Successfully initialize.
---------------------------------
| Loading ServerSide PermaProps |
---------------------------------
permaprops/sv_lib.lua
permaprops/sv_menu.lua
permaprops/sv_permissions.lua
permaprops/sv_specialfcn.lua
permaprops/sv_sql.lua
-----------------------------
| Loading Shared PermaProps |
-----------------------------
---------------------------------
| Loading ClientSide PermaProps |
---------------------------------
permaprops/cl_drawent.lua
permaprops/cl_menu.lua
-------------------------------
Default clips will be not be modified
 +---------------------------------+
 |          E2 EXTENSIONS          |
 +----------------+----------------+
 |    ENABLED     |    DISABLED    |
 +----------------+----------------+
 | console        | constraintcore |
 | file           | effects        |
 | find           | http           |
 | holo           | propcore       |
 | npc            | remoteupload   |
 | pac            | wiring         |
 | ranger         |                |
 | serialization  |                |
 | sound          |                |
 +----------------+----------------+
[GmodAdminSuite] Gamemode initialized
ConVarRef room_type doesn't point to an existing ConVar
Executing dedicated server config file server.cfg
Using map cycle file cfg/mapcycle.txt.
[GmodAdminSuite] InitPostEntity
Initializing Steam libraries for secure Internet server
CAppInfoCacheReadFromDiskThread took 5 milliseconds to initialize
RecordSteamInterfaceCreation (PID 29279): SteamGameServer012 / GameServer
RecordSteamInterfaceCreation (PID 29279): SteamUtils009 / Utils
RecordSteamInterfaceCreation (PID 29279): SteamGameServer012 / 
RecordSteamInterfaceCreation (PID 29279): SteamUtils009 / 
RecordSteamInterfaceCreation (PID 29279): SteamNetworking005 / 
RecordSteamInterfaceCreation (PID 29279): SteamGameServerStats001 / 
RecordSteamInterfaceCreation (PID 29279): STEAMHTTP_INTERFACE_VERSION003 / 
RecordSteamInterfaceCreation (PID 29279): STEAMINVENTORY_INTERFACE_V003 / 
RecordSteamInterfaceCreation (PID 29279): STEAMUGC_INTERFACE_VERSION012 / 
RecordSteamInterfaceCreation (PID 29279): STEAMAPPS_INTERFACE_VERSION008 / 
No account token specified; logging into anonymous game server account.  (Use sv_setsteamaccount to login to a persistent account.)
RecordSteamInterfaceCreation (PID 29279): SteamGameServer012 / 
RecordSteamInterfaceCreation (PID 29279): SteamUtils009 / 
RecordSteamInterfaceCreation (PID 29279): SteamNetworking005 / 
RecordSteamInterfaceCreation (PID 29279): SteamGameServerStats001 / 
RecordSteamInterfaceCreation (PID 29279): STEAMHTTP_INTERFACE_VERSION003 / 
RecordSteamInterfaceCreation (PID 29279): STEAMINVENTORY_INTERFACE_V003 / 
RecordSteamInterfaceCreation (PID 29279): STEAMUGC_INTERFACE_VERSION012 / 
RecordSteamInterfaceCreation (PID 29279): STEAMAPPS_INTERFACE_VERSION008 / 
CApplicationManagerPopulateThread took 236 milliseconds to initialize (will have waited on CAppInfoCacheReadFromDiskThread)
WRITE GROUP: 3
WRITE GROUP: 31
WRITE GROUP: 13
WRITE GROUP: 17
WRITE GROUP: 11
WRITE GROUP: 3
WRITE GROUP: 13
WRITE GROUP: 15
WRITE GROUP: 32
WRITE GROUP: 12
WRITE GROUP: 32
WRITE GROUP: 42
WRITE GROUP: 35
WRITE GROUP: 64
WRITE GROUP: 22
WRITE GROUP: 23
WRITE GROUP: 3
WRITE GROUP: 11
WRITE GROUP: 13
WRITE GROUP: 1
WRITE GROUP: 13
WRITE GROUP: 30
WRITE GROUP: 26
WRITE GROUP: 1
WRITE GROUP: 403
WRITE GROUP: 25
WRITE GROUP: 29
WRITE GROUP: 23
WRITE GROUP: 3
WRITE GROUP: 9
WRITE GROUP: 9
WRITE GROUP: 9
WRITE GROUP: 5
WRITE GROUP: 4
WRITE GROUP: 13
WRITE GROUP: 86
WRITE GROUP: 29
WRITE GROUP: 3
WRITE GROUP: 73
WRITE GROUP: 243
WRITE GROUP: 34
WRITE GROUP: 6
WRITE GROUP: 4
WRITE GROUP: 9
WRITE GROUP: 29
WRITE GROUP: 27
WRITE GROUP: 49
WRITE GROUP: 33
WRITE GROUP: 40
WRITE GROUP: 7
WRITE GROUP: 13
WRITE GROUP: 147
WRITE GROUP: 46
WRITE GROUP: 16
WRITE GROUP: 2
WRITE GROUP: 1
WRITE GROUP: 1
WRITE GROUP: 12
WRITE GROUP: 11
WRITE GROUP: 6
WRITE GROUP: 8
WRITE GROUP: 1
WRITE GROUP: 29
WRITE GROUP: 2
WRITE GROUP: 2
WRITE GROUP: 4
WRITE GROUP: 6
WRITE GROUP: 1
WRITE GROUP: 12
WRITE GROUP: 11
WRITE GROUP: 5
WRITE GROUP: 18
WRITE GROUP: 18
WRITE GROUP: 12
WRITE GROUP: 8
WRITE GROUP: 29
WRITE GROUP: 102
WRITE GROUP: 5
WRITE GROUP: 11
WRITE GROUP: 2
WRITE GROUP: 1
WRITE GROUP: 2
WRITE GROUP: 21
WRITE GROUP: 6
WRITE GROUP: 2
WRITE GROUP: 6
WRITE GROUP: 1
WRITE GROUP: 46
WRITE GROUP: 4
WRITE GROUP: 14
WRITE GROUP: 24
WRITE GROUP: 3
WRITE GROUP: 5
WRITE GROUP: 4
WRITE GROUP: 7
WRITE GROUP: 10
WRITE GROUP: 10
WRITE GROUP: 5
WRITE GROUP: 5
WRITE GROUP: 133
WRITE GROUP: 3
WRITE GROUP: 11
WRITE GROUP: 6
WRITE GROUP: 2
WRITE GROUP: 8
WRITE GROUP: 18
WRITE GROUP: 8
WRITE GROUP: 10
WRITE GROUP: 35
WRITE GROUP: 27
WRITE GROUP: 11
WRITE GROUP: 26
WRITE GROUP: 19
WRITE GROUP: 10
WRITE GROUP: 2
WRITE GROUP: 61
WRITE GROUP: 6
WRITE GROUP: 1
WRITE GROUP: 1
WRITE GROUP: 1
Total time[parse definitions]: 809.685
Connection to Steam servers successful.
   Public IP is blahblahlah.asdf.
Assigned anonymous gameserver Steam ID [A-1:3907572744(16045)].
VAC secure mode is activated.
Spawning textscreens...
RecordSteamInterfaceCreation (PID 29279): STEAMHTTP_INTERFACE_VERSION003 / HTTP
RecordSteamInterfaceCreation (PID 29279): STEAMHTTP_INTERFACE_VERSION003 / HTTP
RecordSteamInterfaceCreation (PID 29279): STEAMHTTP_INTERFACE_VERSION003 / HTTP
RecordSteamInterfaceCreation (PID 29279): STEAMHTTP_INTERFACE_VERSION003 / HTTP
RecordSteamInterfaceCreation (PID 29279): STEAMHTTP_INTERFACE_VERSION003 / HTTP
RecordSteamInterfaceCreation (PID 29279): STEAMHTTP_INTERFACE_VERSION003 / HTTP
RecordSteamInterfaceCreation (PID 29279): STEAMHTTP_INTERFACE_VERSION003 / HTTP
RecordSteamInterfaceCreation (PID 29279): STEAMHTTP_INTERFACE_VERSION003 / HTTP
RecordSteamInterfaceCreation (PID 29279): STEAMHTTP_INTERFACE_VERSION003 / HTTP
RecordSteamInterfaceCreation (PID 29279): STEAMHTTP_INTERFACE_VERSION003 / HTTP
RecordSteamInterfaceCreation (PID 29279): STEAMHTTP_INTERFACE_VERSION003 / HTTP
RecordSteamInterfaceCreation (PID 29279): STEAMHTTP_INTERFACE_VERSION003 / HTTP
RecordSteamInterfaceCreation (PID 29279): STEAMHTTP_INTERFACE_VERSION003 / HTTP
RecordSteamInterfaceCreation (PID 29279): STEAMHTTP_INTERFACE_VERSION003 / HTTP
RecordSteamInterfaceCreation (PID 29279): STEAMHTTP_INTERFACE_VERSION003 / HTTP
RecordSteamInterfaceCreation (PID 29279): STEAMHTTP_INTERFACE_VERSION003 / HTTP
RecordSteamInterfaceCreation (PID 29279): STEAMHTTP_INTERFACE_VERSION003 / HTTP
RecordSteamInterfaceCreation (PID 29279): STEAMHTTP_INTERFACE_VERSION003 / HTTP
RecordSteamInterfaceCreation (PID 29279): STEAMHTTP_INTERFACE_VERSION003 / HTTP
RecordSteamInterfaceCreation (PID 29279): STEAMHTTP_INTERFACE_VERSION003 / HTTP
RecordSteamInterfaceCreation (PID 29279): STEAMHTTP_INTERFACE_VERSION003 / HTTP
RecordSteamInterfaceCreation (PID 29279): STEAMHTTP_INTERFACE_VERSION003 / HTTP
RecordSteamInterfaceCreation (PID 29279): STEAMHTTP_INTERFACE_VERSION003 / HTTP
RecordSteamInterfaceCreation (PID 29279): STEAMHTTP_INTERFACE_VERSION003 / HTTP
RecordSteamInterfaceCreation (PID 29279): STEAMHTTP_INTERFACE_VERSION003 / HTTP
RecordSteamInterfaceCreation (PID 29279): STEAMHTTP_INTERFACE_VERSION003 / HTTP
RecordSteamInterfaceCreation (PID 29279): STEAMHTTP_INTERFACE_VERSION003 / HTTP
RecordSteamInterfaceCreation (PID 29279): STEAMHTTP_INTERFACE_VERSION003 / HTTP
RecordSteamInterfaceCreation (PID 29279): STEAMHTTP_INTERFACE_VERSION003 / HTTP
RecordSteamInterfaceCreation (PID 29279): STEAMHTTP_INTERFACE_VERSION003 / HTTP
RecordSteamInterfaceCreation (PID 29279): STEAMHTTP_INTERFACE_VERSION003 / HTTP
RecordSteamInterfaceCreation (PID 29279): STEAMHTTP_INTERFACE_VERSION003 / HTTP
RecordSteamInterfaceCreation (PID 29279): STEAMHTTP_INTERFACE_VERSION003 / HTTP
RecordSteamInterfaceCreation (PID 29279): STEAMHTTP_INTERFACE_VERSION003 / HTTP
RecordSteamInterfaceCreation (PID 29279): STEAMHTTP_INTERFACE_VERSION003 / HTTP
RecordSteamInterfaceCreation (PID 29279): STEAMHTTP_INTERFACE_VERSION003 / HTTP
RecordSteamInterfaceCreation (PID 29279): STEAMHTTP_INTERFACE_VERSION003 / HTTP
RecordSteamInterfaceCreation (PID 29279): STEAMHTTP_INTERFACE_VERSION003 / HTTP
RecordSteamInterfaceCreation (PID 29279): STEAMHTTP_INTERFACE_VERSION003 / HTTP
RecordSteamInterfaceCreation (PID 29279): STEAMHTTP_INTERFACE_VERSION003 / HTTP
RecordSteamInterfaceCreation (PID 29279): STEAMHTTP_INTERFACE_VERSION003 / HTTP
RecordSteamInterfaceCreation (PID 29279): STEAMHTTP_INTERFACE_VERSION003 / HTTP
RecordSteamInterfaceCreation (PID 29279): STEAMHTTP_INTERFACE_VERSION003 / HTTP
RecordSteamInterfaceCreation (PID 29279): STEAMHTTP_INTERFACE_VERSION003 / HTTP
RecordSteamInterfaceCreation (PID 29279): STEAMHTTP_INTERFACE_VERSION003 / HTTP
RecordSteamInterfaceCreation (PID 29279): STEAMHTTP_INTERFACE_VERSION003 / HTTP
RecordSteamInterfaceCreation (PID 29279): STEAMHTTP_INTERFACE_VERSION003 / HTTP
RecordSteamInterfaceCreation (PID 29279): STEAMHTTP_INTERFACE_VERSION003 / HTTP
</pre>
</details>

**Comment by robotboy655** [comment]
It's likely an issue with your locally running Steam client. If you would not run it, this should not display.

Basically it's a Steam issue as far as I am concerned. Nothing about our SteamAPI version or its usage has changed recently.

**Comment by garryspins** [comment]
You cant run gmod without steam open, maybe the native version but the native version is unplayable so i run it with proton, is there nothing i can do otherwise? @robotboy655

**Comment by robotboy655** [comment]
You do not need Steam to be running for the dedicated server which is where you reported your issue.

**Comment by garryspins** [comment]
I should've explained better
I'm using a local server for development directly on my machine, if i cant run gmod and srcds at the same time that kind of ruins the point, also ive tried running srcds without steam open and i dont get the errors i mentioned above so that seems to have done something different but when i do go to open up gmod it doesnt appear in any form of lan browser

**Comment by garryspins** [comment]
i receiving this error though
`[S_API FAIL] Tried to access Steam interface SteamUser020 before SteamAPI_Init succeeded.` right before its trying to get all the workshop addons to maybe it could be something to do with that

**Comment by robotboy655** [comment]
Should be fixed tomorrow with a Steam Client update.

**Comment by garryspins** [comment]
Alright, its been 3 days since you said that and it still hasnt been fixed, is there anything that i can do/can be done?

**Comment by robotboy655** [comment]
No. It has been confirmed by Valve that it is an issue on their side.

**Comment by garryspins** [comment]
mk :)

**Comment by garryspins** [comment]
I love how its been more than 2 weeks and this still isnt fixed lmao

**Comment by robotboy655** [comment]
It was fixed on 21st of December via a Steam Client update.

**Comment by garryspins** [comment]
The errors havent been fixed but atleast its joinable now

**Comment by robotboy655** [comment]
It's not something we can address. You will have to bother Steam/Valve.
