### ISSUE TITLE
Hammer editor bugs and issues

### ISSUE THREAD

**Issue by JokerR3310** [Facepunch/garrysmod-issues#4856]
### Details

1. Right or Left mouse button can get stuck while editing displacement (Paint Geometry or Paint Alpha), if during holding right or left mouse button accidentally go outside of 3D View Selection window and then release the button.

2. `info_overlay` and `infodecal` get invalid angles parameter after being moved across the editor.
![4](https://user-images.githubusercontent.com/14869831/109439838-a7fc0200-7a38-11eb-9756-3265b3cff93f.jpg)

3. Hinge Axis parameter in prop_door_rotating is not working.

4. For unknown reason "🗹 World" and "🗹 Face" are both selected in (Face Edit Sheet -> Align box) for some sides on every brush, and cannot be changed.
![2](https://user-images.githubusercontent.com/14869831/109439580-9bc37500-7a37-11eb-84f1-cda8c18a02a0.jpg)

5. --
6. --

7. Brush vertices after saving-loading the map, runs away from the points it assigned to on the smallest grid size (precision loss?)
![3](https://user-images.githubusercontent.com/14869831/109439594-a8e06400-7a37-11eb-8bf6-a05d3effcb1c.jpg)

8. Hammer in 3D Map Preview ignores the custom Detail vbsp files from worldspawn entity: "Detail.vbsp file" and "Detail material file" and does not show details in Map Preview, but everything work in game after map is compiled.

**Comment by MARK2580** [comment]
@JokerR3310 Recently, my info_decal model began to appear inside the wall, and not from the side on which the decal was applied )))
As for Face and World, in my opinion I remember this bug even in 2010, when I started my career as a Source modder)

**Comment by robotboy655** [comment]
3. Is by design
4. I will need an example .vmf with the issue to debug it
5. Has nothing to do with Hammer
6. Has nothing to do with Hammer
7. Probably unfixable, but again, a .vmf (and the position) with the issue would be necessary to debug.

Please do not pile on issues into 1 "thread". Separate each problem into its own request/issue.

**Comment by JokerR3310** [comment]
Sorry about piling them up, i will create separate thread for **5** and **6**

4 - The problem is on every brush on any map, for example if i create simple box with 6 sides, 3 of them will have Face and World selected all the time, other 3 will work normal.
![unnamed2222](https://user-images.githubusercontent.com/14869831/109859938-33a6a600-7c66-11eb-8f30-26d4172ba7f9.png)
Exaple vmf link: https://drive.google.com/file/d/1u4tKn5c8huLV4SJy0GQsz4EdI8IvRBcI/view?usp=sharing

7 - And here is the same thing, any brush with many vertices close to ecah other on any map with smallest grid size

Exaple vmf link: https://drive.google.com/file/d/1a7FHpcsDWuI2FYFPBgO8jJ-9ly1YK-wh/view?usp=sharing

**Comment by robotboy655** [comment]
1 & 2 fixed.
4 Looks like intentional. There's no actual difference between the 2 alignments for those 3 faces, which is why they are both ticked, and it makes sense too, even if it is a bit counter-intuitive. All textures are initially face aligned, but only 3 of the faces are facing in the same direction as the 3 world axises (X Y and Z) If you rotate the box the "issue" goes away. You will notice that with texture lock enabled it will auto correct the texture scrolling when rotating.

**Comment by robotboy655** [comment]
I fixed both points on 8 on "dev" beta, but "detail material" seems to be broken (unrelated to the fix), it is not 1:1 to what appears in game, seems to be flipped for some materials. Idk.

**Comment by JokerR3310** [comment]
Yeah, I see that. 
![grass](https://user-images.githubusercontent.com/14869831/110029012-a84c1400-7d3c-11eb-8a1c-b8e76f3b6b88.jpg)

But for some reason if too many "grass" is rendered at once, all "grass" start to blinking like crazy, similar to $treesway ingame shader bug, but this is complete different story.
![grass_bug](https://user-images.githubusercontent.com/14869831/110029805-96b73c00-7d3d-11eb-91fc-0fc2c7a17c31.jpg)

**Comment by JokerR3310** [comment]
I notice hammer 3D preview ignoring `detailorientation <int>` parameter inside detail.vbsp file. But works correctly in the game.

**Comment by JokerR3310** [comment]
2. `info_overlay` and `infodecal` are still getting invalid angles parameter, but this time after being rotated.
![6](https://user-images.githubusercontent.com/14869831/110237942-75c23700-7f47-11eb-8fd6-b3da8a114a73.jpg)

**Comment by robotboy655** [comment]
It's not invalid if you rotate the decal...

**Comment by JokerR3310** [comment]
info_overlay unlike infodecal support rotation, why it's invalid in the first place

**Comment by robotboy655** [comment]
Again, it's not "invalid", it is just not registered in the .fgd that it supports rotation.

**Comment by JokerR3310** [comment]
Yes, that's exacly what i mean by saing "invalid", sorry for misunderstanding.
In that case is it possible to synchronize "physical info_overlay body" and its "decal projection" rotation ? so angle can be also set thru "Object Properties" menu ?

**Comment by robotboy655** [comment]
* `infodecal`: The `angles` keyvalue is not supported by it, but it does show up if you rotate the entity manually. It appears in red because it is not supported by the "entity". I will not be looking into this further, as there's no point. It's a very minor non-issue. Simply not rotating entities that do not support rotation is fix enough.
* `info_overlay`: Pretty much the same story, but rotating it will transform the overlay points. There are no internal `angles`, the key value does nothing like with `infodecal`. Fixing this may not be possible or is very tricky at risk of it acting incorrectly. It's simply not worth the effort. It works well enough as it is.
* Addendum to issue #4: The reason why you cannot select "Face" or "World" separately at all times is because this is not actually saved to the VMF. The value for these checkboxes is generated on the fly when you open/refresh the `Face Sheet` window.
* Feel free to create a new issue for detail props not being 1:1 between hammer and the game, but I likely won't be looking into that for before the next game update. I consider the issues raised in point 8 to be resolved.
* Do not post new comments about other Hammer problems here, create new issues.
* I am not sure the brush vertices losing precision issue can be fixed without extra hacks like what https://github.com/crashfort/HammerPatch does (which is error prone itself) or completely changing how ,vmf files save.
