### ISSUE TITLE
MsgC logs no color on Linux 32-bit/64-bit and Windows 64-bit dedicated Server in the server console

### ISSUE THREAD

**Issue by SmollClover** [Facepunch/garrysmod-issues#6174]
### Details
I've been using a dedicated server for developing Addons for a bit now on my Linux machine and something that has been bugging me for quite a while now, is that there is no color output in the Terminal no matter what I try. I have tried the normal version of the server and even the x86-64 beta in the hopes it would change anything. I tried running the server binary itself with no wrapper script, I tried omitting certain arguments and even adding some. Yet no matter what combination of things I try, the output of the console in my terminal always remains plain white while my terminal definitely supports displaying colors, seeing that every other program works perfectly fine.

I am pretty sure this is a bug, seeing that a friend of mine running a GMod dedicated server on windows has color output in their server console, yet I couldn't find anything on this. Not a single issue with someone mentioning this, even though it makes the console look really cluttered when everything is white even when you try to color log messages to make them pop out when needed.

### Steps to reproduce
1. Setup a dedicated server on a linux machine using the official guide in the wiki (https://wiki.facepunch.com/gmod/Linux_Dedicated_Server_Hosting)
2. Start the server with whatever arguments
3. Watch as the logs are plain white even when a addon tries to print a message with color (it always shows white, no matter what color it is trying to use)

**Comment by LEON-BROTHER** [comment]
Yea, color works for Windows on the 32 Bit version but not on the x86-64 beta version.

**Comment by robotboy655** [comment]
Fixed for Windows on x86-64 beta. 

As I understand it, on Linux there are no colors on both `x86-64` and `dev` and other betas, including main/public version, correct?

**Comment by SmollClover** [comment]
> As I understand it, on Linux there are no colors on both `x86-64` and `dev` and other betas, including main/public version, correct?

Correct. None of the versions, be it x86-64, dev, or any of the other betas, show any colored output.

**Comment by neico** [comment]
Ideally, the engine would be using [ANSI Escape Sequence](https://en.wikipedia.org/wiki/ANSI_escape_code#Colors) to handle console color, ex. `"\x1b[0m"`

Windows is the only exception here, which didn't support those until [Win10 1511](https://learn.microsoft.com/en-us/windows/console/console-virtual-terminal-sequences).
For those older cases the `SetConsoleAttribute()` calls can be used as fallbacks, simply check for [`IsWindows10OrGreater()`](https://learn.microsoft.com/en-us/windows/win32/api/versionhelpers/nf-versionhelpers-iswindows10orgreater)

**Comment by robotboy655** [comment]
I have applied a change to `x86-64` with 24 bit color support, it works on Windows, but I have not tested Linux, would appreciate if you do.

**Comment by SmollClover** [comment]
Just updated my Server, and even tried pulling a completely new one down too (x86-64 beta Linux), but both still don't display any color. All of the text is still as white as can be no matter what color was set.

Here's even a picture of some Text I know is normally colored by default when the dedicated server is on Windows, but even that isn't colored on Linux.
![Image](https://github.com/user-attachments/assets/90d7414e-161a-4a12-a085-3e0bb31c815b)

**Comment by robotboy655** [comment]
Does your terminal support 24bit color sequences? (As linked in the wiki page above)

I will look more into it tomorrow.

**Comment by SmollClover** [comment]
Yep. Every other program I run has no issues showing colors, including a test script that displays several possible 24-bit color sequences.

![Image](https://github.com/user-attachments/assets/46bb516a-deb6-4fa1-862e-5ffdaf3631e7)

**Comment by Cynosphere** [comment]
Works fine using WezTerm on Windows via SSH into a Linux host, GMod running on latest x86-64, both through normal execution and `tmux`. It "works" through `screen` as well but all the colors are broken, which is expected as `screen` only supports 16 colors regardless of `$TERM`.

**Comment by neico** [comment]
[This repository](https://github.com/termstandard/colors) has some more info on the various places it works, can be made to work, or doesn't work.
According to that, `screen` can be made to work with `truecolor` if the version is recent enough. (v5+ or so?)

**Comment by robotboy655** [comment]
It appears to work correctly with Konsole, the default terminal in Kubuntu. (Besides the fact that color is not cleared, which I will fix)

![Image](https://github.com/user-attachments/assets/e9f00621-662c-4067-a8c1-404b09d29737)

**Comment by SmollClover** [comment]
> It appears to work correctly with Konsole, the default terminal in Kubuntu. (Besides the fact that color is not cleared, which I will fix)

Just updated the Server on my end and tried it out and I can also confirm that it's now working. All Text which should be colored now seems to be and in my case it also resets the text color as it should.
