### ISSUE TITLE
Newer updates broke speed on replay and players

### ISSUE THREAD

**Issue by FiBzYY** [Facepunch/garrysmod-issues#6204]
New update broke speed fully on replay bots and spectator

Something with the updates broke gmods speed as you can see from the video all servers on bhop now have this problem, its a issues with the game this never happened before so now we cant see speed correctly this worked since 2014 until now

code:
https://github.com/Snappey/Bhop/blob/master/gamemode/modules/sv_bot.lua

maybe something broke MOVETYPE_NONE ?

this used to work for bots recordings for speed

heres the video:

[https://www.youtube.com/watch?v=aAUHu7KXVyE](url)

Tested on all servers i tried to recode it so it works again but nothing fixes it since its deeply rooted in the game engine, and i know this because ive tested it and cl_showpos 2 should show the speed correctly now its not moving at all and its stuck

![Image](https://github.com/user-attachments/assets/1b1c22ea-339f-47ec-b461-aa9d778161c2)

hopefully this gets fixed also it seems HUDPaintBackground isnt working correctly its no longer updating every frame? ive tested it and it no longer spam console meaning its broken its just not updating every frame like it used to.

MOVETYPE_NONE now fully stop physics updates (velocity, movement, etc.).
Spectator mode no longer sync velocity updates correctly.
Bot movement tracking might be broken unless explicitly updated....

**Comment by robotboy655** [comment]
I have reverted recent changes that probably caused this to happen, please confirm the issue is fixed.

**Comment by robotboy655** [comment]
If by recent you mean 3-4 months ago, then yes, there were changes to how `GetVelocity()` functions on the client. Although, if you are up to date on the client and the server, it should not be noticeable.

Can you link the gamemode and the map, as well as provide steps to reproduce the issue?

When you say "32bit" do you mean 32bit build of the `x86-64` beta, or "NONE" beta?

What is the issue EXACTLY? Just cl_showpos not showing velocity when spectating? That's it?

**Comment by FiBzYY** [comment]
Yeah then that broke the way speed displays on recordings, yes I mean NONE" beta, it seems that when you use W or other keys its 0 updates but if you use a and d ect it updates so poorly and is incorrect, this should be fixed as it doesn't happen at all on NONE branch

Gamemode: 
https://github.com/GMSpeedruns/Flow-Release/tree/master/Gamemodes/Flow%20Network%20-%20All%20gamemodes/Flow%20Network%20-%20Bunny%20Hop

Note its not just this gamemode its any gamemode that has a recording of player and you use GetVelocity in HUD, so any time you make a recording playback speed WILL not update correctly

What is the issue EXACTLY?

Issue: GetVelocity doesn't update correctly on 64 bit but works fine on NONE. if the recordings record player using W +A and W+D or just W no A AND D keys speed is always 0, but if you only use A AND D it updates little bit but at slow rates this never happened before and its proven bug on 64 Branch since it doesn't happen on beta NONE:

As well as provide steps to reproduce the issue?

Instead of setting up this gamemode and testing it your self you would have to set up SQLOO etc. but there's an easy way to test this yourself just load up GMod on 64x branch vs NONE and join any Bunny Hop server with Bots in the server, do !spec or f2 and view the replay you will see a HUD on the bottom left showing speed. Just change to 64x branch vs NONE and test it like that.

Load up gmod on NONE, join a bunny hop gamemode server with bots,

Do !spec watch a BOT view speed on HUD

Repeat the steps on 64x branch next

As you will see something is off with now speed is updated on 64x and it shouldn't be like this

cl_showpos 1 isnt really helpful since it seems it shows recordings velocity even with 0 vel on pos

What this means for DEVs and coders like me, now we cant make recordings of players movements and show the HUDs speed of them without using NONE branch this is annoying and it just shouldn't be like this. 

Now we need to manually "fakevelcioty", network it to the client from replay code since HUD will not update it correctly but this still doesn't fix the problem.


My guesses its a client issue by recent updates edited/changes the way velocity updates on the client

``` local ob = lp():GetObserverTarget()
ob:GetVelocity():Length2D() ```

No longer works correctly on recodings like it used unless you revert to NONE branch.

Considering the server can be updated on 64 bit and i run GMOD on NONE its back and working I'm guessing its client sided problem,

use 64X branch on a 64 server = Broken recording speed, speed never updates right and W ect keys always give 0
Use NONE branch on a 64x server = Working normally GetObserverTarget, GetVelocity updates speeds perfect on recordings

**Comment by robotboy655** [comment]
Ok, I think I understand, the issue is that your code never sets the velocity for the player bots, it just teleports the bot around, so obviously when the server sends the velocity from server to client, it's gonna be 0.

I will make it revert to the old behavior if you set the movetype of a player to NONE.

**Comment by FiBzYY** [comment]
It's still not fixed, 😣

beta NONE: [https://www.youtube.com/watch?v=oUsuSF2fiMY](https://www.youtube.com/watch?v=oUsuSF2fiMY)

x64 branch: [https://www.youtube.com/watch?v=oUsuSF2fiMY](https://www.youtube.com/watch?v=9-eFMOaRlEc)


Speed is still not displaying right, its never resetting to 0 or showing the correct speed
if you use keys like W or W + S besides A and + D to strafe ect its always showing 0 speed

i would just revert back to the old way Entity:GetVelocity() / LocalPlayer():GetVelocity() used to work

it used to:
Returns the entity's velocity. Actually binds to CBaseEntity::GetAbsVelocity() on the server and C_BaseEntity::EstimateAbsVelocity() on the client.

Review the NONE branch velocity code and update 64x branch to work the same
There is no point in changing it since the only difference now is that its broken

==
    keys like W Only showing 0
    is velocity updating only on A and D strafing
    is speed never resetting to 0 and the correct time
==
